apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: gitea
data:
  MINIO_ROOT_PASSWORD: __MINIO_ROOT_PASSWORD__
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: gitea
data:
  REDIS_PASSWORD: __REDIS_PASSWORD__
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: gitea
data:
  POSTGRES_PASSWORD: __POSTGRES_PASSWORD__
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-secret
  namespace: gitea
data:
  INTERNAL_TOKEN: __INTERNAL_TOKEN__
  JWT_SECRET: __JWT_SECRET__
  LFS_JWT_SECRET: __LFS_JWT_SECRET__
  SECRET_KEY: __SECRET_KEY__
